Update to SlackBuild

diff --git a/iceweasel-esr/iceweasel-esr.SlackBuild b/iceweasel-esr/iceweasel-esr.SlackBuild
--- a/iceweasel-esr/iceweasel-esr.SlackBuild
+++ b/iceweasel-esr/iceweasel-esr.SlackBuild
@@ -22,18 +22,17 @@
 
 # Thanks to the folks at the Mozilla Foundation for permission to
 # distribute this, and for all the great work!  :-)
+#-----------------------------------------------------------------------------------------
 
+cd $(dirname $0) ; CWD=$(pwd)
+
+PKGNAM=iceweasel
 PVERSION=$(basename $(ls firefox-*.tar.?z* | cut -d - -f 2 | rev | cut -f 3- -d . | rev) .source)
 VERSION="60.6.1"
-pkgname="iceweasel"
-packname="iceweasel-esr"
 RELEASEVER=$(echo $VERSION | cut -f 1 -d r | cut -f 1 -d b | cut -f 1 -d e)
 BUILD=${BUILD:-1}
 _brandingver=60.0
 _brandingrel=1
-
-
-
 
 # Specify this variable for a localized build.
 # For example, to build a version of Firefox with Italian support, run
@@ -56,6 +55,19 @@ if [ -z "$ARCH" ]; then
        *) export ARCH=$( uname -m ) ;;
   esac
 fi
+
+# Choose a compiler (gcc/g++ or clang/clang++):
+export CC=${CC:-gcc}
+export CXX=${CXX:-g++}
+
+# Keep memory usage as low as possible when linking:
+SLKLDFLAGS=" -Wl,--as-needed -Wl,--no-keep-memory -Wl,--stats"
+export LDFLAGS="$SLKLDFLAGS"
+export MOZ_LINK_FLAGS="$SLKLDFLAGS"
+
+# Put Rust objects on a diet to keep the linker from running into memory
+# issues (especially on 32-bit):
+export RUSTFLAGS="-Cdebuginfo=0"
 
 # Use PGO?  Doubles the time and drive space requirements for the build,
 # but should provide a performance increase.  How much depends on which
@@ -85,42 +97,28 @@ fi
 PGO=${PGO:-no}
 
 if [ "$ARCH" = "i586" ]; then
-  SLKCFLAGS=""
+  SLKCFLAGS="-Os"
   LIBDIRSUFFIX=""
-  OPTIMIZE=" --enable-optimize=-O1 "
 elif [ "$ARCH" = "i686" ]; then
-  SLKCFLAGS=""
+  SLKCFLAGS="-Os"
   LIBDIRSUFFIX=""
-  OPTIMIZE=" --enable-optimize=-O1 "
 elif [ "$ARCH" = "s390" ]; then
   SLKCFLAGS="-O2"
   LIBDIRSUFFIX=""
-  OPTIMIZE=" --enable-optimize=-O1 "
 elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2"
+  SLKCFLAGS="-O2 -fPIC"
   LIBDIRSUFFIX="64"
-  OPTIMIZE=" --enable-optimize=-O1 "
 elif [ "$ARCH" = "arm" ]; then
   SLKCFLAGS="-O2 -march=armv4 -mtune=xscale"
   LIBDIRSUFFIX=""
-  OPTIMIZE=" --enable-optimize=-O1 "
 elif [ "$ARCH" = "armel" ]; then
   SLKCFLAGS="-O2 -march=armv4t"
   LIBDIRSUFFIX=""
-  OPTIMIZE=" --enable-optimize=-O1 "
 else
   SLKCFLAGS="-O2"
   LIBDIRSUFFIX=""
-  OPTIMIZE=" --enable-optimize=-O1 "
 fi
 
-# Link using gold.  This avoids running out of memory on 32-bit systems, and
-# avoids a recurring build failure with GNU ld on other systems.
-PATH="$(pwd)/gold:$PATH"
-export CC="gcc -B$(pwd)/gold"
-export CXX="g++ -B$(pwd)/gold"
-
-CWD=$(pwd)
 TMP=${TMP:-/tmp}
 PKG=$TMP/package-iceweasel
 OUTPUT=${OUTPUT:-/tmp}
@@ -158,14 +156,21 @@ rm -rf firefox-$VERSION
 rm -rf firefox-unpack
 mkdir firefox-unpack
 cd firefox-unpack
-tar xf $CWD/firefox-$PVERSION.source.tar.?z* || exit 1
+tar xvf $CWD/firefox-$PVERSION.source.tar.?z* || exit 1
 mv * ..
 cd ..
 rm -rf firefox-unpack
 cd firefox-$VERSION || exit 1
 
+# Prevent failures building gkrust by suppressing useless warnings:
+sed -i.allow-warnings -e '/#!\[deny(warnings)\]/a #![allow(unused_imports)]' \
+  servo/components/style/lib.rs
+
 # Retain GTK+ v2 scrolling behavior:
 zcat $CWD/ff.ui.scrollToClick.diff.gz | patch -p1 --verbose || exit 1
+
+# Fix building with latest Rust:
+zcat $CWD/unbreakdocs.diff.gz | patch -p1 --verbose || exit 1
 
 # Fetch localization, if requested
 # https://bugzilla.mozilla.org/show_bug.cgi?id=1256955
@@ -187,13 +192,13 @@ find . \
   \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
   -exec chmod 644 {} \;
   
-brandingdir="$CWD/$pkgname-$_brandingver"
+brandingdir="$CWD/$PKGNAM-$_brandingver"
 
 # Prepare branding for the Iceweasel packages
-mkdir -v browser/branding/$pkgname
+mkdir -v browser/branding/$PKGNAM
 
 # copy the branding files
-cp -va $brandingdir/branding/* browser/branding/$pkgname
+cp -va $brandingdir/branding/* browser/branding/$PKGNAM
 
 # patch
 export QUILT_PATCHES=$brandingdir/patches
@@ -218,15 +223,9 @@ sed -i '\|["]displayName["][:] ["]Flash["]| s|Flash|SWF Player|
        \|installLinux| s|true|false|
       ' browser/base/content/browser-plugins.js
 
-# replace newtab page with abouthome
-# not working in FF 60
-#cat browser/base/content/abouthome/aboutHome.xhtml > browser/base/content/newtab/newTab.xhtml
-#sleep 10
-
-# Load our searchplugins                                                                                                                                                                                                                                                               
+# Load our searchplugins                                                                                    
 rm -rv browser/locales/searchplugins
 cp -av $CWD/searchplugins browser/locales
-
 
 # Disable various components at the source level
 sed -i 's|[;]1|;0|' toolkit/components/telemetry/TelemetryStartup.manifest
@@ -243,8 +242,9 @@ OPTIONS="\
   --enable-alsa \
   --enable-application=browser \
   --enable-default-toolkit=cairo-gtk3 \
+  --enable-linker=gold \
   --enable-startup-notification \
-  $OPTIMIZE \
+  $GOOGLE_API_KEY \
   --enable-strip \
   --enable-cpp-rtti \
   --disable-eme \
@@ -254,7 +254,8 @@ OPTIONS="\
   --with-branding=browser/branding/iceweasel \
   --disable-stylo \
   --disable-stylo-build-bindgen \
-  --disable-debug"
+  --disable-debug \
+  --disable-optimize"
 # Complains about missing APNG support in Slackware's libpng:
 # --with-system-png \
 # This option breaks mozilla-12.0:
@@ -277,7 +278,7 @@ fi
 export MOZ_PHOENIX="1"
 export MOZ_PACKAGE_JSSHELL="1"
 export CFLAGS="$SLKCFLAGS"
-export CXXFLAGS="$SLKCFLAGS"
+export CXXFLAGS="$SLKCFLAGS -fno-delate-null-pointer-checks"
 export MOZ_MAKE_FLAGS="$NUMJOBS"
 
 # Clear some variables that could break the build
@@ -293,23 +294,26 @@ echo ". \$topsrcdir/browser/config/mozconfig" > .mozconfig
 mkdir obj
 echo "mk_add_options MOZ_OBJDIR=$(pwd)/obj" >> .mozconfig
 
-if [ "$MOZLOCALIZE" ]; then
-  echo "mk_add_options MOZ_CO_LOCALES=\"$MOZLOCALIZE\"" >> .mozconfig
+# Tell .mozconfig about the selected compiler:
+echo "export CC=\"${CC}\"" >> .mozconfig
+echo "export CXX=\"${CXX}\"" >> .mozconfig
+
+if [ "$COMPILE_X86_UNDER_X86_64" = "true" ]; then
+  # Compile for i686 under an x86_64 kernel:
+  echo "ac_add_options --host=i686-pc-linux-gnu" >> .mozconfig
+  echo "ac_add_options --target=i686-pc-linux-gnu" >> .mozconfig
 fi
 
-# Write in it the options above
+# Add the $OPTIONS above to .mozconfig:
 for option in $OPTIONS; do echo "ac_add_options $option" >> .mozconfig; done
-
-#echo "export CC=clang" >> .mozconfig
-#echo "export CXX=clang++" >> .mozconfig
-
 
 # https://developer.mozilla.org/en-US/docs/Building_with_Profile-Guided_Optimization
 # Thanks to ArchLinux and Gentoo for the additional hints.
 if [ "$PGO" = "yes" ]; then
   # Do a PGO build, double time and disk space but worth it.
   export MOZ_PGO=1
-  echo "mk_add_options PROFILE_GEN_SCRIPT='EXTRA_TEST_ARGS=10 \$(MAKE) -C \$(MOZ_OBJDIR) pgo-profile-run'" >> .mozconfig
+  echo "mk_add_options PROFILE_GEN_SCRIPT='EXTRA_TEST_ARGS=10 \$(MAKE) -C \$(MOZ_OBJDIR)
+pgo-profile-run'" >> .mozconfig
   export DISPLAY=:99
   # Launch Xvfb to let the profile scripts run in a X session.
   # Ugly note: if the build breaks you may want to do a "killall Xvfb".
@@ -319,30 +323,27 @@ if [ "$PGO" = "yes" ]; then
 else
   # Do a normal build
   echo "ac_add_options --disable-tests" >> .mozconfig
-  # make -f client.mk build || exit 1
   ./mach build || exit 1
 fi
-
-# make -f client.mk install DESTDIR=$PKG || exit 1
 
 ./mach buildsymbols || exit 1
 DESTDIR=$PKG ./mach install || exit 1
 
-install -Dm644 $CWD/vendor.js "$PKG/usr/lib${LIBDIRSUFFIX}/$pkgname/browser/defaults/preferences/vendor.js"
-brandingdir="$CWD/$pkgname-$_brandingver"
+install -Dm644 $CWD/vendor.js "$PKG/usr/lib${LIBDIRSUFFIX}/$PKGNAM/browser/defaults/preferences/vendor.js"
+brandingdir="$CWD/$PKGNAM-$_brandingver"
 
 # install iceweasel icons
 icondir="$PKG/usr/share/icons/hicolor"
 for i in 16 22 24 32 48 64 128 192 256 384; do
-  rsvg-convert -w $i -h $i "$brandingdir/branding/${pkgname}_icon.svg"  -o "$brandingdir/default$i.png"
- install -Dm644 "$brandingdir/default$i.png" "$icondir/${i}x${i}/apps/$pkgname.png"
+  rsvg-convert -w $i -h $i "$brandingdir/branding/${PKGNAM}_icon.svg"  -o "$brandingdir/default$i.png"
+ install -Dm644 "$brandingdir/default$i.png" "$icondir/${i}x${i}/apps/$PKGNAM.png"
 done
 
-install -Dm644 "$brandingdir/branding/${pkgname}_icon.svg" "$icondir/scalable/apps/$pkgname.svg"
+install -Dm644 "$brandingdir/branding/${PKGNAM}_icon.svg" "$icondir/scalable/apps/$PKGNAM.svg"
 # Install Iceweasel desktop
 
 install -d "$PKG/usr/share/applications"  
-install -m644 "$CWD/$pkgname.desktop" "$PKG/usr/share/applications"
+install -m644 "$CWD/$PKGNAM.desktop" "$PKG/usr/share/applications"
 
 
 # We don't need these (just symlinks anyway):
@@ -350,13 +351,17 @@ rm -rf $PKG/usr/lib${LIBDIRSUFFIX}/iceweasel-devel-*
 
 # Nor these:
 rm -rf $PKG/usr/include
-rm -rf $PKG/usr/share/idl
 
-cat $CWD/$pkgname.SlackBuild > $PKG/usr/doc/$pkgname-$VERSION/$pkgname.SlackBuild
-
+cat $CWD/$PKGNAM.SlackBuild > $PKG/usr/doc/$PKGNAM-$VERSION/$PKGNAM.SlackBuild
 
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
 
+# Build the package:
 cd $PKG
-/sbin/makepkg -l y -c n $OUTPUT/$packname-$VERSION-$ARCH-$BUILD$TAG.txz
+makepkg -l y -c n $OUTPUT/${PKGNAM}-${VERSION}-${ARCH}-$BUILD.txz 2>&1 | tee $OUTPUT/makepkg-${PKGNAM}.log
+cd $OUTPUT
+md5sum ${PKGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.txz > ${PKGNAM}-${VERSION}-${ARCH}-$BUILD.txz.md5
+cd -
+cat $PKG/install/slack-desc | grep "^${PKGNAM}" > $OUTPUT/${PKGNAM}-${VERSION}-${ARCH}-BUILD.txt
+
